default_agent: aws_assistant
agents:
  aws_assistant:
    name: aws_assistant
    entrypoint: src/main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::591570009439:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-20be6086cc
      execution_role_auto_create: false
      account: '591570009439'
      region: us-west-2
      ecr_repository: 591570009439.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-aws_assistant
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: aws_assistant-YI9rzR5HNr
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:591570009439:runtime/aws_assistant-YI9rzR5HNr
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-aws_assistant-builder
      execution_role: arn:aws:iam::591570009439:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-20be6086cc
      source_bucket: bedrock-agentcore-codebuild-sources-591570009439-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
